### ISSUE TITLE
Rename to hug

### ISSUE THREAD

**Issue by nhooyr** [cdr/slog#46]
`slog` is funny but I don't think it fits slog's personality. slog feels slow and sloppy but slog is anything but. I think this library could be very successful within the community and I don't want it to be held back by its name.

I like `hug` because of it's major focus on developer UX and the API design.

**Comment by ammario** [comment]
hug is ok but a name that indicates it’s a log is helpful when scanning through code or dependencies.

**Comment by nhooyr** [comment]
That's fair, hug is a little opaque. 🤔

**Comment by nhooyr** [comment]
Since no one else has issues with the name, going to close.
