### ISSUE TITLE
Remove dependency on xerrors

### ISSUE THREAD

**Issue by nhooyr** [cdr/slog#54]

**Comment by nhooyr** [comment]
This means we would lose stack frames for now, which is fine I think given most of our error wraps are easily identifiable via text.

Thoughts @ammario @scsmithr @nathanpotter @coadler

**Comment by coadler** [comment]
I disagree. I find the stack frames extremely helpful, especially in `slog.Human`.

What do we gain from removing xerrors?

**Comment by scsmithr** [comment]
I agree with Colin.

**Comment by nhooyr** [comment]
Sounds good.

Less external dependencies, it's nice to be able to only depend on the stdlib.

**Comment by coadler** [comment]
Really unfortunate it was merged into the stdlib without traces :/

**Comment by nhooyr** [comment]
Agreed
