### ISSUE TITLE
Proposed changes to the narrative 

### ISSUE THREAD

**Issue by davidsalgado** [cdr/slog#55]
1. Reorder sections -> Install > Sample > Why > Features 
2. Change the Why section so it talks about where does slog shine vs where does Uber library fall short
> from: We wanted tighter integration with stdlib's testing package
> to: Tight integration with stdlib's testing package
3. Consider merge the Why and Features section into one. 
4. Users section, consider rephrasing
If your company or project is using slog, feel free to open an issue or PR to amend this list.
vs
Let others know you're using slog, open an issue or PR to amend this list

Hope this helps

DavidS

**Comment by nhooyr** [comment]
> Reorder sections -> Install > Sample > Why > Features

Why shouldn't features be first?

**Comment by nhooyr** [comment]
> Change the Why section so it talks about where does slog shine vs where does Uber library fall short

Agreed 100%.

> Consider merge the Why and Features section into one.

Would prefer against this as Why is verbose and not everyone wants to read it.

> Users section, consider rephrasing

Agreed.

**Comment by davidsalgado** [comment]
hey, apologies for my lack of response but I don't have the notifications. I have the personal preference of starting with the WHY, and I thought that the features could be contained there. Anyway, it was just a personal preference comment
