### ISSUE TITLE
I Get A Garbled results

### ISSUE THREAD

**Issue by uyaddayu** [cdr/slog#75]
2019-12-13 02:02:43.229 ?[34m[INFO]?[0m ?[36m<acc.go:19>?[0m    my message here {?[34m"field_name"?[0m: ?[32m"something or the other"?[0m, ?[34m"some_map"?[0m: {?[34m"nested_fields"?[0m: ?[32m"wowow"?[0m}} ...
  ?[34m"error"?[0m: wrap1:
      main.main
          C:/Users/xxx/Desktop/gotest/acc.go:25
    - wrap2:
      main.main
          C:/Users/xxx/Desktop/gotest/acc.go:26
    - EOF

**Comment by nhooyr** [comment]
There is not enough information here to debug.

What OS are you on? What terminal? It looks like the TTY escape codes are not being interpreted by your terminal.

**Comment by coadler** [comment]
Yea just seems like your terminal isn't interpreting the color escape codes correctly.

That brings the question though, do we have a way to force disable color output like we do the ability to force enable?

**Comment by nhooyr** [comment]
> That brings the question though, do we have a way to force disable color output like we do the ability to force enable?

Redirecting to a file or `cat` should just work.
