### ISSUE TITLE
Switch API to log via ctx instead of to logger struct

### ISSUE THREAD

**Issue by nhooyr** [cdr/slog#84]
Tired of logger argument pollution.

cc @ammario @cmoog

**Comment by ammario** [comment]
I'm definitely in favour of this change now.

1) The alternative is Loggers becoming apart of random objects so their methods have smaller signatures.
1) We already store fields as apart of the context, this fits nicely into that model.
1) Context-based instrumentation is the basis of the built in trace package and OpenCensus.

**Comment by cmoog** [comment]
So if I understand correctly, we'd have the following
```go
func process(ctx context.Context) {
    slog.Info(ctx, "log message")
}
```
Wouldn't you lose the ability to specify the `io.Writer` to which logs are written? You'd be restricted to a single logger implicit with each context.

But all things considered, I'm in favor as well.

**Comment by nhooyr** [comment]
@cmoog You'd create a new context with a new logger that writes to wherever you want.

**Comment by nhooyr** [comment]
i.e `ctx = sloghuman.Make(ctx, os.Stdout)`
