### ISSUE TITLE
Unable to use v2

### ISSUE THREAD

**Issue by hassieswift621** [cdr/slog#88]
I get the following error when trying to import v2 of the logger:
```go get cdr.dev/slog@v2.0.0: cdr.dev/slog@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2```

``` go get cdr.dev/slog@v2.0.1: cdr.dev/slog@v2.0.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2```

**Comment by nhooyr** [comment]
Please import as `cdr.dev/slog/v2` and then things should work as expected.

**Comment by nhooyr** [comment]
We'd recommend sticking with V1 btw, we had some problems with V2 and are reverting master to V1 for now.

**Comment by nhooyr** [comment]
Sorry about that btw, master has been reverted.

**Comment by hassieswift621** [comment]
Thanks :+1:
